version: '3'
services: 
  cassandra0: # main seed
    container_name: "cassandra0"
    image: "cassandra:latest"
    command: /bin/bash -c "sleep 1 && echo ' -- Pausing to let system catch up ... -->' && /docker-entrypoint.sh cassandra -f"
    expose:
      - 7000
      - 7001
      - 7199
      - 9042
      - 9160
  cassandra1: #seed node
    container_name: "cassandra1"
    image: "cassandra:latest"
    command: /bin/bash -c "sleep 30 && echo ' -- Pausing to let system catch up ... -->' && /docker-entrypoint.sh cassandra -f"
    env_file:
      - cassandra.env
    expose:
      - 7000
      - 7001
      - 7199
      - 9042
      - 9160
    ports:
      - "9042:9042"
  cassandra2: #seed node
    container_name: "cassandra2"
    image: "cassandra:latest"
    command: /bin/bash -c "sleep 30 && echo ' -- Pausing to let system catch up ... -->' && /docker-entrypoint.sh cassandra -f"
    env_file:
      - cassandra.env
    expose:
      - 7000
      - 7001
      - 7199
      - 9042
      - 9160