version: '3'
services: 
  cassandra0: # main seed
    container_name: "cassandra0"
    image: "cassandra:latest"
    command: /bin/bash -c "sleep 1 && echo ' -- Pausing to let system catch up ... -->' && /docker-entrypoint.sh cassandra -f"
    expose:
      - 7000
      - 7001
      - 7199
      - 9042
      - 9160
  cassandra1: #seed node
    container_name: "cassandra1"
    image: "cassandra:latest"
    # Main seed take some time to start running, pause..
    command: /bin/bash -c "sleep 30 && echo ' -- Pausing to let system catch up ... -->' && /docker-entrypoint.sh cassandra -f"
    env_file:
      - cassandra.env
    expose:
      - 7000
      - 7001
      - 7199
      - 9042
      - 9160
    ports: # export 9042 to host.
      - "9042:9042"
  #***************************************************
  # Increase docker memory to 6g, to support 3rd host 
  #***************************************************
  cassandra2: #seed node
    container_name: "cassandra2"
    image: "cassandra:latest"
    # Wait for main node to start.
    command: /bin/bash -c "sleep 30 && echo ' -- Pausing to let system catch up ... -->' && /docker-entrypoint.sh cassandra -f"
    env_file:
      - cassandra.env
    expose:
      - 7000
      - 7001
      - 7199
      - 9042
      - 9160